=== demezalan/NDZDH6_MDBPract/NDZDH6_0225/NDZDH6_XMLSchema1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- saját típusok -->
    <xs:element name="egyetemi_rendszer">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="egyetem" type="egyetemTipus" maxOccurs="unbounded" />
                <xs:element name="eloado" type="eloadoTipus" maxOccurs="unbounded" />
                <xs:element name="hallgato" type="hallgatoTipus" maxOccurs="unbounded" />
                <xs:element name="kurzus" type="kurzusTipus" maxOccurs="unbounded" />
                <xs:element name="targy" type="targyTipus" maxOccurs="unbounded" />
                <xs:element name="szerzodes" type="szerzodesTipus" maxOccurs="unbounded" />
                <xs:element name="beiratkozas" type="beiratkozasTipus" maxOccurs="unbounded" />
                <xs:element name="oktat" type="oktatTipus" maxOccurs="unbounded" />
                <xs:element name="reszt_vesz" type="reszt_veszTipus" maxOccurs="unbounded" />
                <xs:element name="eloadas" type="eloadasTipus" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>

        <!-- PK kulcsok -->
        <xs:key name="egyetem_kulcs">
            <xs:selector xpath="egyetem" />
            <xs:field xpath="@om" />
        </xs:key>

        <xs:key name="eloado_kulcs">
            <xs:selector xpath="eloado" />
            <xs:field xpath="@lid" />
        </xs:key>

        <xs:key name="hallgato_kulcs">
            <xs:selector xpath="hallgato" />
            <xs:field xpath="@sid" />
        </xs:key>

        <xs:key name="kurzus_kulcs">
            <xs:selector xpath="kurzus" />
            <xs:field xpath="@kurzuskod" />
        </xs:key>

        <xs:key name="targy_kulcs">
            <xs:selector xpath="targy" />
            <xs:field xpath="@targykod" />
        </xs:key>

        <!-- FK kulcsok -->
        <xs:keyref refer="eloado_kulcs" name="szerzodes_eloado_idegen_kulcs">
            <xs:selector xpath="szerzodes" />
            <xs:field xpath="@lid" />
        </xs:keyref>
        <xs:keyref refer="egyetem_kulcs" name="szerzodes_egyetem_idegen_kulcs">
            <xs:selector xpath="szerzodes" />
            <xs:field xpath="@om" />
        </xs:keyref>

        <xs:keyref refer="hallgato_kulcs" name="beiratkozas_hallgato_idegen_kulcs">
            <xs:selector xpath="beiratkozas" />
            <xs:field xpath="@sid" />
        </xs:keyref>
        <xs:keyref refer="egyetem_kulcs" name="beiratkozas_egyetem_idegen_kulcs">
            <xs:selector xpath="beiratkozas" />
            <xs:field xpath="@om" />
        </xs:keyref>

        <xs:keyref refer="eloado_kulcs" name="oktat_eloado_idegen_kulcs">
            <xs:selector xpath="oktat" />
            <xs:field xpath="@lid" />
        </xs:keyref>
        <xs:keyref refer="targy_kulcs" name="oktat_targy_idegen_kulcs">
            <xs:selector xpath="oktat" />
            <xs:field xpath="@targykod" />
        </xs:keyref>

        <xs:keyref refer="hallgato_kulcs" name="resztvesz_hallgato_idegen_kulcs">
            <xs:selector xpath="reszt_vesz" />
            <xs:field xpath="@sid" />
        </xs:keyref>
        <xs:keyref refer="kurzus_kulcs" name="resztvesz_kurzus_idegen_kulcs">
            <xs:selector xpath="reszt_vesz" />
            <xs:field xpath="@kurzuskod" />
        </xs:keyref>

        <xs:keyref refer="targy_kulcs" name="eloadas_targy_idegen_kulcs">
            <xs:selector xpath="eloadas" />
            <xs:field xpath="@targykod" />
        </xs:keyref>
        <xs:keyref refer="kurzus_kulcs" name="eloadas_kurzus_idegen_kulcs">
            <xs:selector xpath="eloadas" />
            <xs:field xpath="@kurzuskod" />
        </xs:keyref>

    </xs:element>

    <!-- komplex tipusok -->
    <xs:complexType name="egyetemTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string" />
            <xs:element name="elhelyezkedes" type="cimTipus" />
            <xs:element name="elerhetoseg" type="elerhetosegTipus" />
        </xs:sequence>
        <xs:attribute name="om" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="cimTipus">
        <xs:sequence>
            <xs:element name="varos" type="xs:string" />
            <xs:element name="utca" type="xs:string" />
            <xs:element name="hazszam" type="xs:string" /> </xs:sequence>
    </xs:complexType>

    <xs:complexType name="elerhetosegTipus">
        <xs:sequence>
            <xs:element name="telefon" type="xs:string" />
            <xs:element name="email" type="xs:string" />
            <xs:element name="fax" type="xs:string" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="eloadoTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string" />
            <xs:element name="lakcim" type="xs:string" />
            <xs:element name="elerhetoseg" type="elerhetosegTipus" />
            <xs:element name="irodaszam" type="xs:integer" />
        </xs:sequence>
        <xs:attribute name="lid" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="hallgatoTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string" />
            <xs:element name="lakcim" type="cimTipus" />
            <xs:element name="email" type="xs:string" />
            <xs:element name="szuletesi_ido" type="xs:date" />
        </xs:sequence>
        <xs:attribute name="sid" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="kurzusTipus">
        <xs:sequence>
            <xs:element name="nyelv" type="xs:string" />
            <xs:element name="tipus" type="xs:string" />
            <xs:element name="idotartam" type="xs:string" />
            <xs:element name="max_fo" type="xs:integer" />
        </xs:sequence>
        <xs:attribute name="kurzuskod" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="targyTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string" />
            <xs:element name="kredit" type="xs:integer" />
            <xs:element name="kovetelmeny" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="targykod" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="szerzodesTipus">
        <xs:sequence>
            <xs:element name="statusz" type="xs:string" />
            <xs:element name="szervezeti_egyseg" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="lid" type="xs:string" use="required" />
        <xs:attribute name="om" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="beiratkozasTipus">
        <xs:sequence>
            <xs:element name="kepzes_neve" type="xs:string" />
            <xs:element name="statusz" type="xs:string" />
            <xs:element name="tagozat" type="xs:string" />
            <xs:element name="szervezeti_egyseg" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="sid" type="xs:string" use="required" />
        <xs:attribute name="om" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="oktatTipus">
        <xs:attribute name="lid" type="xs:string" use="required" />
        <xs:attribute name="targykod" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="reszt_veszTipus">
        <xs:attribute name="sid" type="xs:string" use="required" />
        <xs:attribute name="kurzuskod" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="eloadasTipus">
        <xs:sequence>
            <xs:element name="idopont" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="targykod" type="xs:string" use="required" />
        <xs:attribute name="kurzuskod" type="xs:string" use="required" />
    </xs:complexType>

</xs:schema>

=== demezalan/NDZDH6_MDBPract/NDZDH6_0225/NDZDH6_XDM1.xml
<?xml version="1.0" encoding="UTF-8"?>

<egyetemi_rendszer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NDZDH6_XMLSchema1.xsd">

    <!-- egyetemek -->
    <egyetem om="1492HU">
        <nev>Budapesti Műszaki és Gazdaságtudományi Egyetem</nev>
        <elhelyezkedes>
            <varos>Budapest</varos>
            <utca>Műegyetem rkp.</utca>
            <hazszam>3</hazszam>
        </elhelyezkedes>
        <elerhetoseg>
            <telefon>+36 1 463-1111</telefon>
            <email>info@mit.bme.hu</email>
            <fax>+36 1 463-1110</fax>
        </elerhetoseg>
    </egyetem>

    <egyetem om="1493HU">
        <nev>Eötvös Loránd Tudományegyetem</nev>
        <elhelyezkedes>
            <varos>Budapest</varos>
            <utca>Pázmány Péter sétány</utca>
            <hazszam>1/A</hazszam>
        </elhelyezkedes>
        <elerhetoseg>
            <telefon>+36 1 411-6500</telefon>
            <email>info@elte.hu</email>
            <fax>+36 1 411-6501</fax>
        </elerhetoseg>
    </egyetem>

    <egyetem om="1494HU">
        <nev>Debreceni Egyetem</nev>
        <elhelyezkedes>
            <varos>Debrecen</varos>
            <utca>Oktatócentrum</utca>
            <hazszam>1</hazszam>
        </elhelyezkedes>
        <elerhetoseg>
            <telefon>+36 52 512-900</telefon>
            <email>info@de.edu</email>
        </elerhetoseg>
    </egyetem>


    <!-- eloadok -->
    <eloado lid="l1">
        <nev>Dr. Kovács Ágnes</nev>
        <lakcim>Budapest, Rákóczi út 10</lakcim>
        <elerhetoseg>
            <telefon>+36 20 123-4567</telefon>
            <email>kovacs.agnes@bme.hu</email>
        </elerhetoseg>
        <irodaszam>324</irodaszam>
    </eloado>

    <eloado lid="l2">
        <nev>Dr. Szabó Péter</nev>
        <lakcim>Debrecen, Kossuth Lajos utca 5</lakcim>
        <elerhetoseg>
            <telefon>+36 30 987-6543</telefon>
            <email>szabo.peter@de.edu</email>
        </elerhetoseg>
        <irodaszam>215</irodaszam>
    </eloado>

    <eloado lid="l3">
        <nev>Dr. Nagy Eszter</nev>
        <lakcim>Szeged, Rákóczi Ferenc utca 15</lakcim>
        <elerhetoseg>
            <telefon>+36 70 555-1234</telefon>
            <email>nagy.eszter@szeged.edu</email>
        </elerhetoseg>
        <irodaszam>108</irodaszam>
    </eloado>


    <!-- hallgatok -->
    <hallgato sid="s1">
        <nev>Kovács László</nev>
        <lakcim>
            <varos>Budapest</varos>
            <utca>Petőfi Sándor</utca>
            <hazszam>10</hazszam>
        </lakcim>
        <email>kovacs.laszlo@bme.hu</email>
        <szuletesi_ido>1995-05-20</szuletesi_ido>
    </hallgato>

    <hallgato sid="s2">
        <nev>Szűcs Eszter</nev>
        <lakcim>
            <varos>Debrecen</varos>
            <utca>Kossuth Lajos utca</utca>
            <hazszam>5</hazszam>
        </lakcim>
        <email>szucs.eszter@de.edu</email>
        <szuletesi_ido>1996-08-15</szuletesi_ido>
    </hallgato>

    <hallgato sid="s3">
        <nev>Horváth Péter</nev>
        <lakcim>
            <varos>Szeged</varos>
            <utca>Rákóczi Ferenc utca</utca>
            <hazszam>15</hazszam>
        </lakcim>
        <email>horvath.peter@szeged.edu</email>
        <szuletesi_ido>1997-03-10</szuletesi_ido>
    </hallgato>


    <!-- kurzusok -->
    <kurzus kurzuskod="k1">
        <nyelv>magyar</nyelv>
        <tipus>előadás</tipus>
        <idotartam>90 perc</idotartam>
        <max_fo>100</max_fo>
    </kurzus>

    <kurzus kurzuskod="k2">
        <nyelv>angol</nyelv>
        <tipus>gyakorlat</tipus>
        <idotartam>60 perc</idotartam>
        <max_fo>30</max_fo>
    </kurzus>

    <kurzus kurzuskod="k3">
        <nyelv>magyar</nyelv>
        <tipus>szeminárium</tipus>
        <idotartam>120 perc</idotartam>
        <max_fo>20</max_fo>
    </kurzus>


    <!-- targyak -->
    <targy targykod="t1">
        <nev>Adatbázisok</nev>
        <kredit>5</kredit>
        <kovetelmeny>GEMAL342B</kovetelmeny>
    </targy>

    <targy targykod="t2">
        <nev>Algoritmusok</nev>
        <kredit>4</kredit>
        <kovetelmeny>GEMAL342A</kovetelmeny>
    </targy>

    <targy targykod="t3">
        <nev>Operációs rendszerek</nev>
        <kredit>6</kredit>
        <kovetelmeny>GEMAL342C</kovetelmeny>
    </targy>


    <!-- szerzodesek -->
    <szerzodes lid="l1" om="1492HU">
        <statusz>aktív</statusz>
        <szervezeti_egyseg>Informatikai Kar</szervezeti_egyseg>
    </szerzodes>

    <szerzodes lid="l2" om="1493HU">
        <statusz>aktív</statusz>
        <szervezeti_egyseg>Természettudományi Kar</szervezeti_egyseg>
    </szerzodes>

    <szerzodes lid="l3" om="1494HU">
        <statusz>aktív</statusz>
        <szervezeti_egyseg>Természettudományi és Informatikai Kar</szervezeti_egyseg>
    </szerzodes>


    <!-- beiratkozasok -->
    <beiratkozas sid="s1" om="1492HU">
        <kepzes_neve>BSc Informatika</kepzes_neve>
        <statusz>aktív</statusz>
        <tagozat>nappali</tagozat>
        <szervezeti_egyseg>Informatikai Kar</szervezeti_egyseg>
    </beiratkozas>

    <beiratkozas sid="s2" om="1493HU">
        <kepzes_neve>BSc Biológia</kepzes_neve>
        <statusz>passzív</statusz>
        <tagozat>nappali</tagozat>
        <szervezeti_egyseg>Természettudományi Kar</szervezeti_egyseg>
    </beiratkozas>

    <beiratkozas sid="s3" om="1494HU">
        <kepzes_neve>BSc Fizika</kepzes_neve>
        <statusz>aktív</statusz>
        <tagozat>levelező</tagozat>
        <szervezeti_egyseg>Természettudományi és Informatikai Kar</szervezeti_egyseg>
    </beiratkozas>

    <beiratkozas sid="s1" om="1493HU">
        <kepzes_neve>BSc Biológia</kepzes_neve>
        <statusz>aktív</statusz>
        <tagozat>nappali</tagozat>
        <szervezeti_egyseg>Természettudományi Kar</szervezeti_egyseg>
    </beiratkozas>


    <!-- oktatasok -->
    <oktat lid="l1" targykod="t1"/>

    <oktat lid="l2" targykod="t2"/>

    <oktat lid="l3" targykod="t3"/>


    <!-- resztvevok -->
    <reszt_vesz sid="s1" kurzuskod="k1"/>

    <reszt_vesz sid="s2" kurzuskod="k2"/>

    <reszt_vesz sid="s3" kurzuskod="k3"/>


    <!-- eloadasok -->
    <eloadas targykod="t1" kurzuskod="k1">
        <idopont>kedd 8:00</idopont>
    </eloadas>

    <eloadas targykod="t2" kurzuskod="k2">
        <idopont>szerda 10:00</idopont>
    </eloadas>

    <eloadas targykod="t3" kurzuskod="k3">
        <idopont>csütörtök 14:00</idopont>
    </eloadas>
        

</egyetemi_rendszer>
